### ISSUE TITLE
Using ES6 features in older browsers

### ISSUE THREAD

**Issue by Chudesnov** [dennybritz/neal-react#11]
Currently available versions of Internet Explorer used in Windows 7, Window 8.1, Windows Phone 8.1 and Windows 10 do not support ES6 (e.g. `Object.assign`) natively, and there are no polyfills included with neal-react for ES6 features it uses.

Due to this issue, a neal-react-based landing page (i.e. nealjs.com) cannot be opened on a Windows phone at all, as there are no third-party browsers for this platform.

**Comment by dennybritz** [comment]
Good point, we should fix this Thanks for filing the issue. I think the only ES6 feature I'm using is `Object.assign` but there really is no reason to other than convenience. Should be easy to take it out.

**Comment by dennybritz** [comment]
I think including the babel polyfill is the easier solution and it makes writing code a bit more pleasant ;) 

26ddbc61210604daf21942dec15fd6cf5dec208c should fix it. Updated the sample page to use the latest version. I don't have an easy way to test it in IE right now, so I'll keep this open until I get around to testing it.

**Comment by Chudesnov** [comment]
It works! Kinda clunky in portrait mode, but that's a different story :)

**Comment by dennybritz** [comment]
Haha, glad that it works at all on IE :D It's an achievement.
