### ISSUE TITLE
Currency symbol from Font Awesome?

### ISSUE THREAD

**Issue by rmuratov** [dennybritz/neal-react#12]
`$` symbol has a wide support of web fonts, but some currency, for example Russian ruble `\u20BD` has not.

It would be nice to be able to select the currency symbol in `pricing-table` component.

Not very familiar with React, tried to do, but unsuccessfully:

``` jsx
<div className="neal-pricing-plan-price-amount"><i className="fa fa-rub"></i> {this.props.price}</div
```

**Comment by dennybritz** [comment]
Great point. Right now the `price` attribute in `PricingPlan` is a string, but it should be a `node` object so that you can pass arbitrary things (like other html tags) to it. Will fix that.

**Comment by dennybritz** [comment]
Now you should be able to do something like:

``` jsx
<PricingTable price={<span><i className="fa fa-rub"/>599</span>} { ... } />
```

**Comment by rmuratov** [comment]
:+1: Thanks a lot.
