### ISSUE TITLE
FF Images on demo are not responsive

### ISSUE THREAD

**Issue by azimgd** [dennybritz/neal-react#15]
Please take a look to this screenshot.
https://www.dropbox.com/s/akydga2wxnchtm3/Screenshot%202015-11-04%2011.31.27.png?dl=0

**Comment by dennybritz** [comment]
Thanks for filing this! Which browser is this? It's looking fine for me in Chrome and Safari, but I don't have access to others right now.

**Comment by azimgd** [comment]
Firefox 41. It indeed looks fine on chrome and safari

**Comment by dennybritz** [comment]
Okay, should be fixed in df4a394833146cfb74a62ec209b84d06a703a3a4. Thanks!
