### ISSUE TITLE
Custom Fields for Signup Modal

### ISSUE THREAD

**Issue by dennybritz** [dennybritz/neal-react#8]
Signup modal should support custom fields besides the default `name` and `email`. How to keep the markup simple but make it flexible?

**Comment by danieljuhl** [comment]
How about using children? If none is provided, it goes with the default.

**Comment by dennybritz** [comment]
Yep, it should definitely be something with the children. But writing form markup is very verbose and there are lots of different types of form inputs (textarea, select, etc). It'd be nice to have a simple markup to define the field with sensible defaults.
